checkpoint_dir: ./weights/mpie250000 # Directory for saving network checkpo0ints
eval_dir: ./output/eval/mpie250000 # Directory for saving metrics, i.e., FID and LPIPS

# model arguments
img_size: 256 # Image resolution
num_domains: 2 # Number of domains
latent_dim: 16 # Latent vector dimension
hidden_dim: 512 # Hidden dimension of mapping network
id_embed_dim: 4096 # ID code dimension by VGGFace
id_embed: false # multi input
# style code dimension
style_dim: 128 # Style code dimension

# loss select
loss: perceptual # the type of loss. [perceptual]
# dataset select
dataset: mpie #  
pix2pix: false # use pix2pix loss
multi_discriminator: true # use multi_discriminator
style_cyc: true # use style consistency loss
arc: false # use arcface loss
meg: false # use arcface loss
shape_loss: true # use shape_id loss
config: configs/mb1_120x120.yml
multi: false # multi input
masks: false # use mask injection
self_att: true # use self-attention
landmark_loss: false # use landmark l1 loss
vgg19_recon_loss: true # use landmark l1 loss

# weight for objective functions
lambda_pixel: 1 # Weight for pixel l1 loss
lambda_fm: 1 # Weight for feature match loss

lambda_style_cyc: 1 # Weight for id style consistency loss

lambda_id: 1 # Weight for id loss
lambda_reg: 1 # Weight for R1 regularization

ds_iter: 10 # Number of iterations to optimize diversity sensitive loss
w_hpf: 1 # weight for high-pass filtering

randcrop_prob: 0.5 # Probabilty of using random-resized cropping

resume_iter: 250000 # Iterations to resume training/testing
batch_size: 1 # Batch size for training
val_batch_size: 16 # Batch size for validation
lr: 1e # Learning rate for D, E and G
f_lr: 1e # Learning rate for F
beta1: 0.0 # Decay rate for 1st moment of Adam
beta2: 0.99 # Decay rate for 2nd moment of Adam
weight_decay: 1e-4 # Weight decay for optimizer
num_outs_per_domain: 1 # Number of generated images per domain during sampling

# misc
mode: eval # This argument is used in solver
num_workers: 0 # Number of workers used in DataLoader
seed: 777 # Seed for random number generator
