name: demo
nets_ema_path: ./weights/demo/204000_nets_ema.ckpt

# model arguments
img_size: 256 # Image resolution
num_domains: 2 # Number of domains
latent_dim: 16 # Latent vector dimension
hidden_dim: 512 # Hidden dimension of mapping network
style_dim: 128 # Style code dimension

# loss select
multi_discriminator: true # use multi_discriminator
multi: false # multi input
masks: false # use mask injection
self_att: true # use self-attention

w_hpf: 1 # weight for high-pass filtering

