name: mpie250000
nets_ema_path: ./weights/mpie250000/nets_ema.ckpt

# model arguments
img_size: 256 # Image resolution
num_domains: 2 # Number of domains
style_dim: 128 # Style code dimension

multi_discriminator: true # use multi_discriminator
multi: false # multi input
masks: false # use mask injection
self_att: true # use self-attention

w_hpf: 1 # weight for high-pass filtering

