defaults:
  - _self_
  - dataset: ???
  - list: ???
  
# Globals
seed: 777
num_workers: 0 # for dataloader
batch_size: 80
output_dir: output
output_label: ${list.name}

# Hydra output config
hydra:
  run:
    dir: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}

